<option value=""></option>
<option>Chittagong</option>
<option>Dhaka</option>
<option>Rajshahi</option>
<option>Sylhet</option>
<option>Jessore</option>
<option>Dinajpur</option>
<option>Mymensingh</option>
<option>Comilla</option>
<option>Barisal</option>
<option>Bogra</option>
<option>Pabna</option>
<option>Rangamati</option>
<option>Kushtia</option>
<option>Rangpur</option>
<option>Noakhali</option>
<option>Khulna</option>
<option>Tangail</option>
<option>Panchagarh</option>
<option>Bhola</option>
<option>Habiganj</option>
<option>Lakshmipur</option>
<option>Barguna</option>
<option>Jhalokati</option>
<option>Pirojpur</option>
<option>Patuakhali</option>
<option>Jhenaidah</option>
<option>Narail</option>
<option>Magura</option>
<option>Lalmonirhat</option>
<option>Kurigram</option>
<option>Nilphamari</option>
<option>Gaibandha</option>
<option>Thakurgaon</option>
<option>Satkhira</option>
<option>Bagerhat</option>
<option>Chuadanga</option>
<option>Meherpur</option>
<option>Sirajganj</option>
<option>Joypurhat</option>
<option>Natore</option>
<option>Naogaon</option>
<option>Nawabganj</option>
<option>Khagrachhari</option>
<option>Feni</option>
<option>Brahmanbaria</option>
<option>Sunamganj</option>
<option>Cox's Bazar</option>
<option>Moulvibazar</option>
<option>Gopalganj</option>
<option>Shariatpur</option>
<option>Madaripur</option>
<option>Rajbari</option>
<option>Gazipur</option>
<option>Kishoreganj</option>
<option>Jamalpur</option>
<option>Sherpur</option>
<option>Netrakona</option>
<option>Munshiganj</option>
<option>Narsingdi</option>
<option>Narayanganj</option>
<option>Manikganj</option>